# docker-compose up -d
version: "3.9"

services:
  app:
    image: nginx
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./app:/app
    depends_on:
      - api

  api:
    image: node:14
    restart: always
    working_dir: /api
    command: bash -c "npm i && npm run prod"
    expose:
      - 3000
    volumes:
      - ./api:/api
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./db_data:/data/db
